[package]
name = "zweb"
version = "0.1.0"
edition = "2024"

[dependencies]
wry = "0.55"
tao = "0.35"
windows = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Graphics_Dwm",
    "Win32_System_Registry",
] }